const badgesNiceNames = [
  'apprentice',
  'scullion',
  'mini-cooker',
  'cooker',
  'chef',
  'video-amateur-cook',
  'the-cook-of-the-tv',
  'aim-for-that-oscar',
  'questioner',
  'talking-between-the-stove',
  'tertullian-of-the-kitchen',
  'to-the-soup-of-letters',
  'applied',
  'photogenic',
  'mycook-tiny-star',
  'mycook-supernova',
  'attractive',
  'seductive',
  'irresistible',
  'ebook-writer',
];
export default badgesNiceNames;
